site_name: My Docs
theme:
  name: material
  palette:
    scheme: slate
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  - toc.integrate

nav:
  - Home: index.md
  - Genetec:
    - Server setup: genetec/server_setup.md
    - Client setup: genetec/client_setup.md
    - How to add a camera: genetec/add_a_camera.md
    - Camera controls: genetec/camera_controls.md
  - Axis:
    - Assign an IP-adres: axis/ip_settings/assign_IP.md
    - Update camera: axis/update_os/update_camera.md
    - Add new user: axis/new_user/add_user.md
    - Setup a radar: axis/radar_setup/radar_setup.md
  - Mobiqam: 
    - Troubleshooting: mobiqam/troubleshooting/troubleshooting.md
  - Internal tools:
    - SafeLaunch:
      - How to prep: SafeLaunch/how_to_prep.md
      - Install on location: SafeLaunch/install_on_location.md
    - SafeSign:
      - How to prep: SafeSign/how_to_prep.md


  - Switches:
    - Edgeswitch:
      - Troubleshooting commands: troubleshooting_commands_ES.md
    - FS-switch:
      - Troubleshooting commands: troubleshooting_commands_FS.md
  - MikroTik:
    - Event setup: event_setup.md
  - Tools:
    - fping: tools/fping.md
    - Windows setup: tools/windows_setup.md